name: CI - Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: lanchonete
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: preto321
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Rodar testes
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MERCADOPAGO_ACCESS_TOKEN: ${{ secrets.MERCADOPAGO_TOKEN }}
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/lanchonete
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
          run: mvn test